Tuan4_LinQ2_XuanPhuong/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tuan4_LinQ2_XuanPhuong.Models;
using PagedList;

namespace Tuan4_LinQ2_XuanPhuong.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(int? page)
        {
            //var all_sach = from s in data.Saches select s;
            //return View(all_sach);
            //return View();
            //----
            if (page == null) page = 1;
            var all_sach = (from s in data.Saches select s).OrderBy(m => m.masach);
            int pagesize = 6;
            int pagenum = page ?? 1;
            return View(all_sach.ToPagedList(pagenum,pagesize));
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        // GET : Order
        MyDataDataContext data = new MyDataDataContext();
        

    }
}

Tuan4_LinQ2_XuanPhuong/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tuan4_LinQ2_XuanPhuong.Models;

namespace Tuan4_LinQ2_XuanPhuong.Controllers
{
    public class SachController : Controller
    {
        // GET: Sach
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult ListSach()
        {
            var all_sach = from ss in data.Saches select ss;
            return View(all_sach);
        }
        // ---------------- Detail ----------------------
        public ActionResult Detail(int id)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            return View(D_sach);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, Sach s)
        {
            var E_tensach = collection["tensach"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.tensach = E_tensach.ToString();
                s.hinh = E_hinh.ToString();
                s.giaban = E_giaban;
                s.ngaycapnhat = E_ngaycapnhat;
                s.soluongton = E_soluongton;
                data.Saches.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Create();
        }
        public ActionResult Edit(int id)
        {
            var E_sach = data.Saches.First(m => m.masach == id);
            return View(E_sach);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_sach = data.Saches.First(m => m.masach == id);
            var E_tensach = collection["tensach"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycatnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            E_sach.masach = id;
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                E_sach.tensach = E_tensach;
                E_sach.hinh = E_hinh;
                E_sach.giaban = E_giaban;
                E_sach.ngaycapnhat = E_ngaycapnhat;
                E_sach.soluongton = E_soluongton;
                UpdateModel(E_sach);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Edit(id);
        }
        //-----------------------------------------
        public ActionResult Delete(int id)
        {
            var D_sach = data.Saches.First(m => m.masach == id);
            return View(D_sach);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            data.Saches.DeleteOnSubmit(D_sach);
            data.SubmitChanges();
            return RedirectToAction("ListSach");
        }
    }
}

Tuan4_LinQ2_XuanPhuong/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Tuan4_LinQ2_XuanPhuong/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr style="color :red" title="Phone">Phone:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">phuong.yoshino@gmail.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">phuong.yoshino@gmail.com</a>
</address>

Tuan4_LinQ2_XuanPhuong/Views/Home/Index.cshtml
@model PagedList.IPagedList<Tuan4_LinQ2_XuanPhuong.Models.Sach>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>HUTECH SÁCH</h2>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="panel panel-default">
                <div class="panel panel-heading">
                    @item.tensach
                </div>
                <div class="panel-body">
                    <p><strong>Giá: </strong>@item.giaban</p>
                    <p><strong>Ngày cập nhật: </strong>@item.ngaycapnhat</p>
                    <p><strong>Số lượng tồn: </strong>@item.soluongton</p>
                    <p><img width="300px" src="@item.hinh" alt="hinh thumnail"></p>

                    26

                </div>
                <div class="panel-footer clearfix">
                    <div class="pull-right">
                        <a href="#" class="btn btn-primary">Order</a>
                        @Html.ActionLink("Read more...", "Detail", "Sach", new { id = item.masach }, new { @class = "btn btn-default" })
                        @* @Html.ActionLink("Mua", "Order", "Sach", new { id = item.masach }, new { @class = "btn btn-default" })*@
                        <div class="DatMua">
                            <a class="btn btn-success" href="@Url.Action("ThemGioHang", "GioHang",
new { @id = item.masach, @strURL = Request.Url.ToString() })">Đặt mua</a>
                        </div>
                        @*                        @Html.ActionLink("Read More...", "Detail", new { id = item.Id }, new { @class = "btn btn-default" })*@
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div>
    <div>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) /
        @Model.PageCount
    </div>
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new{ page = page}))
    </div>
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>
<style type="text/css">
    #mau-nut a {
        clear: both;
        background-color: orange;
        color: snow;
    }

        #mau-nut a:hover {
            background-color: darkcyan;
            color: snow;
        }
</style>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
$(document).ready(function () {
var maxLength = 100;
$(".show-read-more").each(function () {
var myStr = $(this).text();
if ($.trim(myStr).length > maxLength) {
var newStr = myStr.substring(0, maxLength);
var removedStr = myStr.substring(maxLength, $.trim(myStr).length);
$(this).empty().html(newStr);

$(this).append(' <a href="javascript:void(0);" class="read-
more">đọc tiếp...</a>');

$(this).append('<span class="more-text">' + removedStr +
'</span>');
}
});
$(".read-more").click(function () {
$(this).siblings(".more-text").contents().unwrap();

27

$(this).remove();
});
});
</script>
<style>
    .show-read-more .more-text {
        display: none;
    }
</style>